In [3]:
# NumPy and Pandas Assignment
# Complete the following tasks by filling in the code where indicated.
# Ensure your notebook is well-documented with markdown cells explaining your code and result.
import numpy as np
import pandas as pd


# Task 1: NumPy Basics

### Array Creation
#### 1. Create an array of 10 zeros but set the fifth element to 1.


In [ ]:
# solution
def array_creation():
    arr = pd.Series([0] * 10)
    arr.iloc[4] = 1
    return arr
my_array = array_creation()
print(my_array)






### 2. Create a 4x4 matrix with values ranging from 0 to 15.



In [ ]:
# solution
def matrix_creation():
    matrix = np.arange(16).reshape(4, 4)
    return matrix
matrix_arr = matrix_creation()
print(matrix_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


### Array Operations

#### 3. Create two NumPy arrays: Perform element-wise addition, subtraction, multiplication, and division.
#### arr1: array([[41, 30, 10], [ 6, 35, 23], [23,  9, 10]])
#### arr2: array([[4, 29,  2], [5, 13,  3], [24, 16,  7]])

In [51]:
# solution
arr1 = np.array([[41, 30, 10], [6, 35, 23], [23, 9, 10]])
arr2 = np.array([[4, 29, 2], [5, 13, 3], [24, 16, 7]])
def array_operatoins(a, b):
    addition = arr1 + arr2
    subtraction = arr1 - arr2
    multiplication = arr1 * arr2
    division = arr1 / arr2 
    return addition, subtraction, multiplication, division
calculation = array_operatoins(arr1, arr2)


print(calculation)


(array([[45, 59, 12],
       [11, 48, 26],
       [47, 25, 17]]), array([[37,  1,  8],
       [ 1, 22, 20],
       [-1, -7,  3]]), array([[164, 870,  20],
       [ 30, 455,  69],
       [552, 144,  70]]), array([[10.25      ,  1.03448276,  5.        ],
       [ 1.2       ,  2.69230769,  7.66666667],
       [ 0.95833333,  0.5625    ,  1.42857143]]))


### Array Slicing
#### 4. Given the array: 
#### arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
#### Extract elements from index 2 to 6.

In [13]:
# Creating a NumPy array
def slicing_array():
    arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])  
    output = arr[2:6]
    return output  

slice_elements = slicing_array()

print(slice_elements)

[30 40 50 60]


### Using NumPy Methods
#### 5. Convert the array below to a 3×3 NumPy array.
#### array([[15, 18, 20], [15, 30, 8], [25, 30, 60]])
#### Find the mean, sum, and maximum value.

In [ ]:
# solution
arrays = np.array([[15,18,20],[15,30,8],[25,30,60]])
# NB: round the mean to two decimal places
def mean_of_array(arr):
    mean = np.mean(arrays)
    sum = np.sum(arrays)
    max = np.max(arrays)
    print("Mean of the array is: ", mean)
    print("Sum of the array is: ", sum)
    print("Max of the array is: ", max)
    return round(mean, 2)
mean = mean_of_array(arrays)
mean


Mean of the array is:  24.555555555555557
Sum of the array is:  221
Max of the array is:  60


24.56

# Task 2: Pandas Basics

### Creating a Pandas Series
#### 1. Create a Pandas Series from the list [10, 20, 30, 40, 50] with index labels 'a', 'b', 'c', 'd', 'e'.

In [15]:
# solution
def pandas_series():
    data = [10, 20, 30, 40, 50]
    index = ['a', 'b', 'c', 'd', 'e']
    series = pd.Series(data,index)
    return series
my_series = pandas_series()
print(my_series)

a    10
b    20
c    30
d    40
e    50
dtype: int64


### Reading a CSV File
#### 2. Read a CSV file named "data.csv" into a Pandas DataFrame. The CSV file has the following columns: "Name", "Age", "Salary".

In [ ]:
# solution
def read_csv_datas():
	df = pd.read_csv("data/data.csv")
	return df

dfa = read_csv_datas()
print(dfa.columns)
print(df1)

df = dfa.rename(columns={"Salary": "Score"}, inplace = False)
df.columns

Index(['Name', 'Age', 'Salary'], dtype='object')


### Slicing a DataFrame
#### 3. From the DataFrame created in Exercise 2, select only the first three rows.

In [ ]:
# solution
def select_rows(df):
    first_three_rows = df.head(3)
    return first_three_rows
first_three_rows = select_rows(dfa)
print(first_three_rows)

      Name  Age  Salary
0    Alice   29   73193
1      Bob   53   85398
2  Charlie   36   47162


### Manipulating a DataFrame - Adding a Column
#### 4. Add a new column named "Tax" to the DataFrame from Exercise 2. The tax should be calculated as 10% of the "Salary" column.

In [52]:
# solution

def add_column(df, column_name):
    df[column_name] = df['Salary'] * 0.10
    return df
new_column = add_column(dfa,"Tax")
print(new_column)


       Name  Age  Salary     Tax
0     Alice   29   73193  7319.3
1       Bob   53   85398  8539.8
2   Charlie   36   47162  4716.2
3     David   22   65853  6585.3
4       Eve   24   36168  3616.8
5     Frank   58   69657  6965.7
6     Grace   41   85202  8520.2
7    Hannah   38   62421  6242.1
8     Isaac   50   74641  7464.1
9      Jack   47   38963  3896.3
10    Karen   34   32136  3213.6
11      Leo   49   41874  4187.4
12     Mona   56   34070  3407.0
13     Nina   49   91734  9173.4
14    Oscar   30   89539  8953.9
15     Paul   23   78720  7872.0
16    Quinn   31   54424  5442.4
17   Rachel   54   59900  5990.0
18    Steve   36   32163  3216.3
19     Tina   56   52054  5205.4


#### Filter the dataframe by the column "age" whereby the age is above 36 years

In [25]:
# solution
def filter_age_condition(df):
    age_filter = df[df['Age'] > 36]
    return age_filter
age_filter = filter_age_condition(dfa)
print(age_filter)

      Name  Age  Salary     Tax
1      Bob   53   85398  8539.8
5    Frank   58   69657  6965.7
6    Grace   41   85202  8520.2
7   Hannah   38   62421  6242.1
8    Isaac   50   74641  7464.1
9     Jack   47   38963  3896.3
11     Leo   49   41874  4187.4
12    Mona   56   34070  3407.0
13    Nina   49   91734  9173.4
17  Rachel   54   59900  5990.0
19    Tina   56   52054  5205.4


# Task 3: Data Analysis with Pandas

### Aggregation - Compute Total and Mean Sales
#### 1. Given a dataset of sales transactions, compute the total and mean sales per region.

In [26]:
# Sample Data
sales_data = pd.DataFrame({
    "Region": ["North", "South", "North", "West", "South", "West"],
    "Sales": [1000, 1500, 1200, 1800, 1300, 1700]
})
sales_data.head()



Region  Sales
0  North   1000
1  South   1500
2  North   1200
3   West   1800
4  South   1300

In [57]:
# solution
def total_mean_sales(df):
    total_sales = df.groupby('Region').sum()
    mean_sales = df.groupby('Region').mean()
    return total_sales, mean_sales
total_sales, mean_sales = total_mean_sales(sales_data)
sales_data.columns=['Total Sales', 'Mean Sales']
print(sales_data)

  Total Sales  Mean Sales
0       North        1000
1       South        1500
2       North        1200
3        West        1800
4       South        1300
5        West        1700


### Merging - Combine Customer and Order Data
#### 2. Merge customers and orders data based on CustomerID.

In [59]:
customers = pd.DataFrame({
    "CustomerID": [1, 2, 3, 4],
    "CustomerName": ["Alice", "Bob", "Charlie", "David"]
})

orders = pd.DataFrame({
    "OrderID": [101, 102, 103, 104],
    "CustomerID": [1, 2, 2, 4],
    "Amount": [250, 400, 600, 150]
})

print(customers.head(2), "\n", orders.head(2))


   CustomerID CustomerName
0           1        Alice
1           2          Bob 
    OrderID  CustomerID  Amount
0      101           1     250
1      102           2     400


In [31]:
# solution
def merge_dataframes(cust, ord):
    merged_data = pd.merge(cust, ord, on='CustomerID', how='inner')
    return merged_data
merged_data = merge_dataframes(customers, orders)
print(merged_data)


   CustomerID CustomerName  OrderID  Amount
0           1        Alice      101     250
1           2          Bob      102     400
2           2          Bob      103     600
3           4        David      104     150


### Joining - Left Join Employee Data
#### 4. Perform a left join between employees and departments on DeptID.

In [61]:
# NB: No test for this. Just an exercise for you to play around with
employees = pd.DataFrame({
    "EmpID": [101, 102, 103, 104],
    "EmpName": ["John", "Jane", "Alice", "Bob"],
    "DeptID": [1, 2, 2, 3]
})

departments = pd.DataFrame({
    "DeptID": [1, 2],
    "DeptName": ["HR", "Finance"]
})

print(employees.head(2),"\n\n", departments.head(2))


   EmpID EmpName  DeptID
0    101    John       1
1    102    Jane       2 

    DeptID DeptName
0       1       HR
1       2  Finance


In [33]:
# solution

def left_join(df1, df2):
    left_joined = pd.merge(df1, df2, on='DeptID', how='left')
    return left_joined
left_joined = left_join(employees, departments)
print(left_joined)

   EmpID EmpName  DeptID DeptName
0    101    John       1       HR
1    102    Jane       2  Finance
2    103   Alice       2  Finance
3    104     Bob       3      NaN


### Pivot Table - Summarize Sales Data
#### 4. Create a pivot table showing total sales for each Region and Product.

In [38]:
sales_pivot_data = pd.DataFrame({
    "Region": ["North", "North", "South", "South", "West", "West"],
    "Product": ["A", "B", "A", "B", "A", "B"],
    "Sales": [200, 300, 150, 400, 250, 500]
})

sales_pivot_data.head(2)

Region Product  Sales
0  North       A    200
1  North       B    300

In [62]:
# solution
# Create a pivot table showing total sales for each Region and Product.
def create_pivot_table(df):
    pivot_table = df.pivot_table(index='Region', columns='Product', values='Sales', aggfunc='sum')
    return pivot_table
pivot_table = create_pivot_table(sales_pivot_data)
print(pivot_table)


Product    A    B
Region           
North    200  300
South    150  400
West     250  500
